version: 2.1

orbs:
  node: circleci/node@4.0.1

defaults: &defaults
  docker:
    - image: circleci/node:10-browsers
      environment:
        JOBS: 1

jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
<% if (yarn) { %>          pkg-manager: "yarn"<% } %>
          cache-version: "v1"
          include-branch-in-cache-key: false
<% if (exam && !addon) { %>      - run:
          name: Prebuild Ember app for tests
          command: yarn ember build --environment=testing
<% } else if (exam === false) { %>      - run:
          name: Generate reports folder
          command: mkdir reports
<% } %>      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint Handlebars
          command: <% if (yarn) { %>yarn<% } else { %>npm run<% } %> lint:hbs
      - run:
          name: Lint JavaScript
          command: <% if (yarn) { %>yarn<% } else { %>npm run<% } %> lint:js

  test:
    <<: *defaults
<% if (addon) { %>    parameters:
      scenario:
        type: enum
        enum:
          [
            "lts-3.12",
            "lts-3.16",
            "lts-3.20",
            "release",
            "beta",
            "canary",
            "default",
            "default-with-jquery",
            "classic",
          ]
        default: "default"
<% }
if (exam) { %>    parallelism: <%= parallel %>
<% } %>    steps:
      - attach_workspace:
          at: .
<% if (addon) { %>      - when:
          condition:
            equal: [ "default", << parameters.scenario >> ]
          steps:
            - run:
                name: Run << parameters.scenario >> Tests
                command: <% if (yarn) { %>yarn<% } else { %>npm run<% } %> test:ember
      - when:
          condition:
            not:
              equal: [ "default", << parameters.scenario >> ]
          steps:
            - run:
                name: Run << parameters.scenario >> Tests
                command: <% if (yarn) { %>yarn <% } else { %>npm <% } %><% if (addon) { %>ember try:one ember-<< parameters.scenario >> --skip-cleanup=true<% } else if (exam) { %>ember exam --path=dist --split=$CIRCLE_NODE_TOTAL --partition=`expr $CIRCLE_NODE_INDEX + 1` --parallel --load-balance<% } else if (yarn) { %>test:ember<% } else { %>run test:ember<% } %>
<% } else { %>      - run:
          name: Run Tests
          command: <% if (yarn) { %>yarn <% } else { %>npm <% } %><% if (exam) { %>ember exam --path=dist --split=$CIRCLE_NODE_TOTAL --partition=`expr $CIRCLE_NODE_INDEX + 1` --parallel --load-balance<% } else { if (!yarn) { %>run <% } %>test:ember<% } %>
<% } if (exam === false) { %>      - store_test_results:
          path: "reports"
      - store_artifacts:
          path: "reports"
<% } %>
workflows:
  <% if (addon) { %>test_matrix:<% } else { %>build_and_test:<% } %>
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - test:
          requires:
            - prepare<% if (addon) { %>
      - test:
          name: test_lts_3_12
          scenario: lts-3.12
          requires:
            - lint
            - test
      - test:
          name: test_lts_3_16
          scenario: lts-3.16
          requires:
            - lint
            - test
      - test:
          name: test_lts_3_20
          scenario: lts-3.20
          requires:
            - lint
            - test
      - test:
          name: test_release
          scenario: release
          requires:
            - lint
            - test
      - test:
          name: test_beta
          scenario: beta
          requires:
            - lint
            - test
      - test:
          name: test_canary
          scenario: canary
          requires:
            - lint
            - test
      - test:
          name: test_default_with_jquery
          scenario: "default-with-jquery"
          requires:
            - lint
            - test
      - test:
          name: test_classic
          scenario: classic
          requires:
            - lint
            - test<% } %>
