defaults: &defaults
  docker:
    - image: circleci/node:10-browsers
      environment:
        JOBS: 2
  working_directory: ~/<%= name %>

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - <%= name %>-node10-v1-{{ checksum "<% if (yarn) { %>yarn.lock<% } else { %>package-lock.json<% } %>" }}
      - run:<% if (yarn) { %>
          name: Yarn Install
          command: yarn install --non-interactive<% } else { %> npm config set spin false
      - run:
          name: NPM Install
          command: npm install<% } %>
      - save_cache:
          key: <%= name %>-node10-v1-{{ checksum "<% if (yarn) { %>yarn.lock<% } else { %>package-lock.json<% } %>" }}
          paths:
            - ~/<%= name %>/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/<%= name %>/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Lint Handlebars
          command: <% if (yarn) { %>yarn lint:hbs<% } else { %>npm run lint:hbs<% } %>
      - run:
          name: Lint JavaScript
          command: <% if (yarn) { %>yarn lint:js<% } else { %>npm run lint:js<% } %>

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/<%= name %>/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: <% if (yarn) { %>yarn test<% } else { %>npm run test<% } %>
<% if (addon) { %>
  test_lts_2_16:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/<%= name %>/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests Ember LTS 2.16
          command: ember try:one ember-lts-2.16 --skip-cleanup=true

  test_lts_2_18:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/<%= name %>/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests Ember LTS 2.18
          command: ember try:one ember-lts-2.18 --skip-cleanup=true

  test_release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/<%= name %>/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests Ember Release
          command: ember try:one ember-release --skip-cleanup=true

  test_beta:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/<%= name %>/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests Ember Beta
          command: ember try:one ember-beta --skip-cleanup=true

  test_canary:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/<%= name %>/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests Ember Canary
          command: ember try:one ember-canary --skip-cleanup=true

  test_default_with_jquery:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/<%= name %>/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests Ember Default With jQuery
          command: ember try:one ember-default-with-jquery --skip-cleanup=true
<% } %>
workflows:
  version: 2
  <% if (addon) { %>test_matrix:<% } else { %>build_and_test:<% } %>
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies<% if (addon) { %>
      - test_lts_2_16:
          requires:
            - install_dependencies
      - test_lts_2_18:
          requires:
            - install_dependencies
      - test_release:
          requires:
            - install_dependencies
      - test_beta:
          requires:
            - install_dependencies
      - test_canary:
          requires:
            - install_dependencies
      - test_default_with_jquery:
          requires:
            - install_dependencies<% } %>
