version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  test:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - node/install-packages<% if (yarn) { %>:
          pkg-manager: yarn<% } %>
      - run:
          name: Lint
          command: <%= yarn ? 'yarn' : 'npm run' %> lint
      - run:
          name: Run Tests
          command: <%= yarn ? 'yarn' : 'npm run' %> <%= exam ? 'ember exam --split=$CIRCLE_NODE_TOTAL --partition=`expr $CIRCLE_NODE_INDEX + 1` --parallel --load-balance' : 'test:ember' %>
<% if (addon) { %>
  floating:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - node/install-packages:
<% if (yarn) { %>          pkg-manager: yarn<% } %>
          override-ci-command: <%= yarn ? 'yarn install --no-lockfile' : 'npm install --no-shrinkwrap' %>
      - run:
          name: Run Tests
          command: <%= yarn ? 'yarn' : 'npm run' %> <%= exam ? 'ember exam --split=$CIRCLE_NODE_TOTAL --partition=`expr $CIRCLE_NODE_INDEX + 1` --parallel --load-balance' : 'test:ember' %>

  try-scenarios:
    docker:
      - image: circleci/node:12-browsers
    parameters:
      scenario:
        type: enum
        enum:
          [
            "ember-lts-3.24",
            "ember-lts-3.28",
            "ember-release",
            "ember-beta",
            "ember-canary",
            "ember-classic",
            "ember-default-with-jquery",
            "embroider-safe",
            "embroider-optimized",
          ]
<% if (exam) { %>    parallelism: <%= parallel %>
<% } %>    steps:
      - checkout
      - node/install-packages<% if (yarn) { %>:
          pkg-manager: yarn<% } %>
<% if (!exam) { %>      - run:
          name: Generate reports folder
          command: mkdir reports<% } %>
      - run:
          name: Run << parameters.scenario >> Tests
          command: <%= yarn ? 'yarn' : 'npm run' %> ember try:one << parameters.scenario >> --skip-cleanup=true
<% if (!exam) { %>      - store_test_results:
          path: "reports"
<% }
} %>
workflows:
  tests:
    jobs:
      - test<% if (addon) { %>
      - floating:
          requires:
            - test
      - try-scenarios:
          name: test-ember-lts-3.24
          scenario: ember-lts-3.24
          requires:
            - test
      - try-scenarios:
          name: test-ember-lts-3.28
          scenario: ember-lts-3.28
          requires:
            - test
      - try-scenarios:
          name: test-ember-release
          scenario: ember-release
          requires:
            - test
      - try-scenarios:
          name: test-ember-beta
          scenario: ember-beta
          requires:
            - test
      - try-scenarios:
          name: test-ember-canary
          scenario: ember-canary
          requires:
            - test
      - try-scenarios:
          name: test-ember-classic
          scenario: ember-classic
          requires:
            - test
      - try-scenarios:
          name: test-ember-default-with-jquery
          scenario: ember-default-with-jquery
          requires:
            - test
      - try-scenarios:
          name: test-embroider-safe
          scenario: embroider-safe
          requires:
            - test
      - try-scenarios:
          name: test-embroider-optimized
          scenario: embroider-optimized
          requires:
            - test<% } %>
