defaults: &defaults
  docker:
    - image: circleci/node:10-browsers
      environment:
        JOBS: 1
  working_directory: ~/<%= name %>

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - <%= name %>-node10-v1-{{ checksum "<% if (yarn) { %>yarn.lock<% } else { %>package-lock.json<% } %>" }}
      - run:<% if (yarn) { %>
          name: Yarn Install
          command: yarn install --non-interactive --pure-lockfile<% } else { %> npm config set spin false
      - run:
          name: NPM Install
          command: npm install<% } %>
      - save_cache:
          key: <%= name %>-node10-v1-{{ checksum "<% if (yarn) { %>yarn.lock<% } else { %>package-lock.json<% } %>" }}
          paths:
            - ~/<%= name %>/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint Handlebars
          command: <% if (yarn) { %>yarn<% } else { %>npm run<% } %> lint:hbs
      - run:
          name: Lint JavaScript
          command: <% if (yarn) { %>yarn<% } else { %>npm run<% } %> lint:js

  test:
    <<: *defaults
<% if (addon && exam) { %>    parallelism: <%= parallel %>
<% } %>    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: <% if (addon) { %><% if (yarn) { %>yarn<% } else { %>npx<% } %> ember try:one ember-default --skip-cleanup=true<% } else if (exam) { %><% if (yarn) { %>yarn<% } else { %>npx<% } %> ember exam --split=$CIRCLE_NODE_TOTAL --partition=`expr $CIRCLE_NODE_INDEX + 1` --parallel --load-balance<% } else if (yarn) { %>yarn test<% } else { %>npm run test<% } %>
<% if (addon) { %>
  test_lts_2_18:
    <<: *defaults
<% if (addon && exam) { %>    parallelism: <%= parallel %>
<% } %>    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests Ember LTS 2.18
          command: <% if (yarn) { %>yarn<% } else { %>npx<% } %> ember try:one ember-lts-2.18 --skip-cleanup=true

  test_lts_3_4:
    <<: *defaults
<% if (addon && exam) { %>    parallelism: <%= parallel %>
<% } %>    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests Ember LTS 3.4
          command: <% if (yarn) { %>yarn<% } else { %>npx<% } %> ember try:one ember-lts-3.4 --skip-cleanup=true

  test_release:
    <<: *defaults
<% if (addon && exam) { %>    parallelism: <%= parallel %>
<% } %>    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests Ember Release
          command: <% if (yarn) { %>yarn<% } else { %>npx<% } %> ember try:one ember-release --skip-cleanup=true

  test_beta:
    <<: *defaults
<% if (addon && exam) { %>    parallelism: <%= parallel %>
<% } %>    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests Ember Beta
          command: <% if (yarn) { %>yarn<% } else { %>npx<% } %> ember try:one ember-beta --skip-cleanup=true

  test_canary:
    <<: *defaults
<% if (addon && exam) { %>    parallelism: <%= parallel %>
<% } %>    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests Ember Canary
          command: <% if (yarn) { %>yarn<% } else { %>npx<% } %> ember try:one ember-canary --skip-cleanup=true

  test_default_with_jquery:
    <<: *defaults
<% if (addon && exam) { %>    parallelism: <%= parallel %>
<% } %>    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests Ember Default With jQuery
          command: <% if (yarn) { %>yarn<% } else { %>npx<% } %> ember try:one ember-default-with-jquery --skip-cleanup=true
<% } %>
workflows:
  version: 2
  <% if (addon) { %>test_matrix:<% } else { %>build_and_test:<% } %>
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies<% if (addon) { %>
      - test_lts_2_18:
          requires:
            - install_dependencies
      - test_lts_3_4:
          requires:
            - install_dependencies
      - test_release:
          requires:
            - install_dependencies
      - test_beta:
          requires:
            - install_dependencies
      - test_canary:
          requires:
            - install_dependencies
      - test_default_with_jquery:
          requires:
            - install_dependencies<% } %>
